name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./CanedoLab.MS.Identity.API/
    - name: Build
      run: dotnet build --no-restore ./CanedoLab.MS.Identity.API/
    - name: Test
      run: dotnet test --no-build --verbosity normal ./CanedoLab.MS.Identity.API/
